name: Cloud Build CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Make sure this secret contains the correct GCP service account JSON

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: singular-agent-452813-n6  # Add your GCP Project ID here

      - name: Verify Authentication
        run: gcloud auth list  # Debugging step to verify the authentication

      - name: Run Cloud Build
        run: |
          gcloud builds submit --substitutions=_ENV_WELCOME_MESSAGE="${{ secrets.ENV_WELCOME_MESSAGE }}",_ENV_SLEEP_TIME="${{ secrets.ENV_SLEEP_TIME }}",_ENV_PRODUCTION="${{ secrets.ENV_PRODUCTION }}"
